"""
llm_report.py
-------------
Generates a structured underwriter report using GPT-4.1 mini.
Falls back to Gemini Flash if no OpenAI API key is configured.

Pipeline position:
    RuleEngine -> LLMReportGenerator -> (PDF or text report)

The LLM role is STRICTLY limited to:
  - Summarising the risk model output
  - Explaining SHAP factors in plain English
  - Describing fraud flags (if any)
  - Noting the rule engine routing decision

The LLM NEVER:
  - Recommends approving or rejecting the loan
  - Adds opinions beyond what the data shows
  - Fabricates or infers information not provided

Output: a structured UnderwriterReport dict containing sections
that can be rendered as text or passed to pdf_report.py.
"""

from __future__ import annotations

import os
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional

from dotenv import load_dotenv

load_dotenv()


# ---------------------------------------------------------------------------
# UnderwriterReport dataclass
# ---------------------------------------------------------------------------

@dataclass
class UnderwriterReport:
    """
    Structured underwriter report produced by the LLM.

    Attributes
    ----------
    applicant_name       : Extracted from loan fields (or 'Unknown').
    report_timestamp     : ISO datetime string when report was generated.
    llm_provider         : Which LLM was used ('openai' | 'gemini').
    sections             : Ordered dict of section_title -> section_text.
    guardrail            : Mandatory disclaimer reminding that LLM
                           does not make loan decisions.
    raw_llm_output       : Full raw response from the LLM.
    """
    applicant_name: str
    report_timestamp: str
    llm_provider: str
    sections: Dict[str, str]
    guardrail: str = (
        "IMPORTANT: This report was generated by an AI language model for "
        "informational purposes only. It summarises evidence from quantitative "
        "models and does not constitute a loan approval, rejection, or "
        "recommendation. All credit decisions must be made by a qualified "
        "human underwriter."
    )
    raw_llm_output: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return {
            "applicant_name": self.applicant_name,
            "report_timestamp": self.report_timestamp,
            "llm_provider": self.llm_provider,
            "sections": self.sections,
            "guardrail": self.guardrail,
        }

    def to_text(self) -> str:
        """Render the report as a plain-text string."""
        lines = [
            "=" * 70,
            "CREDIT RISK UNDERWRITER REPORT",
            f"Applicant : {self.applicant_name}",
            f"Generated : {self.report_timestamp}",
            f"LLM Model : {self.llm_provider}",
            "=" * 70,
            "",
        ]
        for title, content in self.sections.items():
            lines.append(f"{'─' * 70}")
            lines.append(f"  {title.upper()}")
            lines.append(f"{'─' * 70}")
            lines.append(content.strip())
            lines.append("")
        lines.append("=" * 70)
        lines.append("GUARDRAIL NOTICE")
        lines.append("=" * 70)
        lines.append(self.guardrail)
        return "\n".join(lines)


# ---------------------------------------------------------------------------
# Prompt builder
# ---------------------------------------------------------------------------

def _build_prompt(
    fields: Dict[str, Any],
    prob_default: float,
    risk_tier: str,
    shap_factors: Dict[str, Any],
    fraud_report_dict: Dict[str, Any],
    rule_decision_dict: Dict[str, Any],
) -> str:
    """Build the underwriting prompt from pipeline outputs."""

    # Format SHAP risk drivers
    drivers = shap_factors.get("risk_drivers", [])
    mitigators = shap_factors.get("mitigators", [])

    def fmt_factors(factors: List[Dict]) -> str:
        if not factors:
            return "None identified."
        return "\n".join(
            f"  - {f['feature']} = {f['value']:.4g}  "
            f"(SHAP contribution: {f['shap_contribution']:+.4f})"
            for f in factors
        )

    # Format fraud flags
    flags = fraud_report_dict.get("flags", [])
    if flags:
        fraud_section = "\n".join(
            f"  [{f['severity'].upper()}] {f['check_name']}: {f['description']}"
            for f in flags
        )
    else:
        fraud_section = "  No fraud flags raised."

    # Key extracted fields
    key_fields = {
        "Applicant Name":       fields.get("applicant_name", "Not provided"),
        "Loan Amount":          fields.get("loan_amount"),
        "Annual Income":        fields.get("annual_income"),
        "DTI":                  fields.get("dti"),
        "FICO Score":           fields.get("fico_avg"),
        "Employment Length":    fields.get("employment_length"),
        "Home Ownership":       fields.get("home_ownership"),
        "Loan Purpose":         fields.get("purpose"),
        "Revolving Utilization":fields.get("revolving_utilization"),
        "Delinquencies (2yr)":  fields.get("delinquencies_2yrs"),
        "Public Records":       fields.get("public_records"),
    }
    fields_text = "\n".join(
        f"  {k}: {v}" for k, v in key_fields.items() if v is not None
    )

    return f"""You are an AI assistant for a credit risk platform.
Your ONLY role is to write a factual underwriter summary based on the data provided.

STRICT RULES:
1. Do NOT approve or reject the loan.
2. Do NOT use words like "approve", "reject", "recommend approval", or "recommend rejection".
3. Do NOT invent or infer information not present in the data.
4. Use professional, neutral language suitable for a credit risk report.
5. Each section must be factual and grounded in the data below.

---

APPLICATION DATA:
{fields_text}

---

ML RISK MODEL OUTPUT:
  Probability of Default : {prob_default:.2%}
  Risk Tier              : {risk_tier}

---

TOP SHAP RISK DRIVERS (features pushing default probability UP):
{fmt_factors(drivers)}

TOP SHAP MITIGATORS (features pushing default probability DOWN):
{fmt_factors(mitigators)}

---

FRAUD ASSESSMENT:
  Overall Fraud Risk Level : {fraud_report_dict.get('fraud_risk_level', 'UNKNOWN')}
{fraud_section}

---

RULE ENGINE ROUTING DECISION:
  Verdict          : {rule_decision_dict.get('verdict', 'UNKNOWN')}
  Triggered Rules  : {', '.join(rule_decision_dict.get('triggered_rules', []))}
  Rationale        : {rule_decision_dict.get('rationale', '')}

---

Please write a structured underwriter report with EXACTLY these four sections.
Return only the report text, with each section clearly labelled:

1. APPLICANT OVERVIEW
   Summarise the applicant's key financial profile from the application data.

2. RISK MODEL ANALYSIS
   - Detail the Risk Model context: XGBoost Binary Classifier trained on LendingClub (2007-2018) dataset (Model Evaluation: ROC-AUC: 0.742).
   - State the P(Default) and Risk Tier.
   - List the "Top Risk Drivers" in a distinct sub-list showing their values and SHAP contributions formatted cleanly with dot leaders like:
     • Interest Rate ........ +0.2197
     • Loan Amount .......... +0.0680
     • Loan-to-Income ....... +0.0335
   - List the "Top Positive Drivers" in a distinct sub-list showing their values and SHAP contributions formatted cleanly with dot leaders like:
     • Loan Term ............ -0.0412
     • Low DTI .............. -0.0285
     • Strong FICO .......... -0.0214
   - Explain what these factors mean in plain English for this applicant's risk profile.

3. FRAUD & ANOMALY ASSESSMENT
   Summarise the fraud flags raised (or confirm a clean profile if none).

4. ROUTING DECISION SUMMARY
   State the rule engine verdict and briefly explain what it means for
   the underwriter's next steps. Do NOT add a recommendation beyond
   what the rule engine already decided.
""".strip()


# ---------------------------------------------------------------------------
# LLMReportGenerator
# ---------------------------------------------------------------------------

class LLMReportGenerator:
    """
    Generates an underwriter report using GPT-4.1 mini (primary)
    or Gemini Flash (fallback when OpenAI key is unavailable).

    Usage
    -----
        generator = LLMReportGenerator()
        report = generator.generate(
            fields=extractor_result["fields"],
            prob_default=0.18,
            risk_tier="Medium",
            shap_factors=shap_factors_dict,
            fraud_report=fraud_report,
            rule_decision=rule_decision,
        )
        print(report.to_text())
    """

    OPENAI_MODEL  = "gpt-4.1-mini"
    GEMINI_MODEL  = "gemini-2.5-flash"

    def __init__(self):
        self.openai_key = os.getenv("OPENAI_API_KEY", "").strip()
        self.gemini_key = os.getenv("GEMINI_API_KEY", "").strip()
        self._provider  = None  # set on first generate()

    def _use_openai(self) -> bool:
        return bool(self.openai_key)

    def generate(
        self,
        fields: Dict[str, Any],
        prob_default: float,
        risk_tier: str,
        shap_factors: Dict[str, Any],
        fraud_report: Any,   # FraudReport or dict
        rule_decision: Any,  # RuleDecision or dict
    ) -> UnderwriterReport:
        """
        Generate and return an UnderwriterReport.

        Parameters
        ----------
        fields        : Extracted loan fields dict.
        prob_default  : Float 0–1 from RiskModelPredictor.
        risk_tier     : String tier label ('Low'|'Medium'|'High'|'Very High').
        shap_factors  : Dict from SHAPExplainer.get_top_risk_factors().
        fraud_report  : FraudReport object or equivalent dict.
        rule_decision : RuleDecision object or equivalent dict.
        """
        # Normalise to dicts
        fraud_dict  = fraud_report.to_dict()  if hasattr(fraud_report,  "to_dict") else fraud_report
        rule_dict   = rule_decision.to_dict() if hasattr(rule_decision, "to_dict") else rule_decision

        prompt = _build_prompt(
            fields=fields,
            prob_default=prob_default,
            risk_tier=risk_tier,
            shap_factors=shap_factors,
            fraud_report_dict=fraud_dict,
            rule_decision_dict=rule_dict,
        )

        if self._use_openai():
            raw_text = self._call_openai(prompt)
            provider = "GPT-4.1 mini"
        elif self.gemini_key:
            raw_text = self._call_gemini(prompt)
            provider = "Gemini Flash"
        else:
            raise RuntimeError(
                "No LLM API key found. Set OPENAI_API_KEY or GEMINI_API_KEY in .env"
            )

        sections = self._parse_sections(raw_text)

        return UnderwriterReport(
            applicant_name=fields.get("applicant_name") or "Unknown Applicant",
            report_timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            llm_provider=provider,
            sections=sections,
            raw_llm_output=raw_text,
        )

    # ------------------------------------------------------------------
    # LLM callers
    # ------------------------------------------------------------------

    def _call_openai(self, prompt: str) -> str:
        from openai import OpenAI
        client = OpenAI(api_key=self.openai_key)
        response = client.chat.completions.create(
            model=self.OPENAI_MODEL,
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are a professional credit risk analyst assistant. "
                        "You write factual, structured underwriter reports. "
                        "You never approve or reject loans."
                    ),
                },
                {"role": "user", "content": prompt},
            ],
            temperature=0.2,
            max_tokens=1500,
        )
        return response.choices[0].message.content.strip()

    def _call_gemini(self, prompt: str) -> str:
        from google import genai
        from google.genai import types

        client = genai.Client(api_key=self.gemini_key)
        model_id = f"models/{self.GEMINI_MODEL}"
        response = client.models.generate_content(
            model=model_id,
            contents=prompt,
            config=types.GenerateContentConfig(
                temperature=0.2,
                max_output_tokens=1500,
                system_instruction=(
                    "You are a professional credit risk analyst assistant. "
                    "You write factual, structured underwriter reports. "
                    "You never approve or reject loans."
                ),
            ),
        )
        return response.text.strip()

    # ------------------------------------------------------------------
    # Section parser
    # ------------------------------------------------------------------

    def _parse_sections(self, raw_text: str) -> Dict[str, str]:
        """
        Parse the four expected sections from the LLM output.
        Falls back to a single 'Full Report' section if parsing fails.
        """
        section_mappings = {
            "APPLICANT OVERVIEW": [
                "APPLICANTOVERVIEW", "OVERVIEW"
            ],
            "RISK MODEL ANALYSIS": [
                "RISKMODELANALYSIS", "RISKMODEL", "RISKANALYSIS"
            ],
            "FRAUD & ANOMALY ASSESSMENT": [
                "FRAUD&ANOMALYASSESSMENT", "FRAUDANDANOMALYASSESSMENT",
                "FRAUD&ANOMALY", "FRAUDANDANOMALY", "FRAUDASSESSMENT", "FRAUD&ANOMALIES"
            ],
            "ROUTING DECISION SUMMARY": [
                "ROUTINGDECISIONSUMMARY", "ROUTINGSUMMARY", "ROUTINGDECISION"
            ],
        }

        sections: Dict[str, str] = {}
        current_title: Optional[str] = None
        current_lines: List[str] = []

        for line in raw_text.splitlines():
            stripped = line.strip()
            if not stripped:
                if current_title:
                    current_lines.append(line)
                continue

            # Normalize the line: uppercase, replace AND with &
            norm_line = stripped.upper().replace("AND", "&")
            
            # Clean leading non-alphanumeric characters (like #, *, -, spaces)
            cleaned_start = stripped.lstrip("#*- \t")

            matched_title = None
            if len(stripped) < 60:
                # 1. First check: Does this line start with an explicit section digit?
                # e.g., "2. RISK MODEL ANALYSIS (ROC-AUC: 0.742)" or "### 3. Fraud Checks"
                if cleaned_start and cleaned_start[0].isdigit():
                    digit = cleaned_start[0]
                    # Get letters & ampersand only for containment checks
                    clean_norm = "".join(c for c in norm_line if c.isalpha() or c == "&")
                    if digit == "1" and "OVERVIEW" in clean_norm:
                        matched_title = "APPLICANT OVERVIEW"
                    elif digit == "2" and "RISK" in clean_norm:
                        matched_title = "RISK MODEL ANALYSIS"
                    elif digit == "3" and "FRAUD" in clean_norm:
                        matched_title = "FRAUD & ANOMALY ASSESSMENT"
                    elif digit == "4" and ("ROUTING" in clean_norm or "DECISION" in clean_norm):
                        matched_title = "ROUTING DECISION SUMMARY"

                # 2. Second check: Fallback to exact/startswith match on aliases (no digit required)
                if not matched_title:
                    clean_line = "".join(c for c in norm_line if c.isalpha() or c == "&")
                    
                    # Strip structural prefixes
                    for prefix in ["SECTION", "PART", "STEP", "CHAPTER"]:
                        if clean_line.startswith(prefix):
                            clean_line = clean_line[len(prefix):]
                            
                    # Strip leading digits
                    while clean_line and clean_line[0].isdigit():
                        clean_line = clean_line[1:]

                    for title_key, aliases in section_mappings.items():
                        for alias in aliases:
                            # Normalize alias
                            clean_alias = alias.upper().replace("AND", "&")
                            clean_alias = "".join(c for c in clean_alias if c.isalpha() or c == "&")
                            
                            # Match if exact
                            if clean_line == clean_alias:
                                matched_title = title_key
                                break
                        if matched_title:
                            break

            if matched_title:
                # Save previous section
                if current_title:
                    sections[current_title] = "\n".join(current_lines).strip()
                current_title = matched_title
                current_lines = []
            else:
                if current_title:
                    current_lines.append(line)

        # Save last section
        if current_title:
            sections[current_title] = "\n".join(current_lines).strip()

        # Fallback
        if not sections:
            sections["Full Report"] = raw_text

        return sections


# ---------------------------------------------------------------------------
# Convenience function
# ---------------------------------------------------------------------------

def generate_report(
    fields: Dict[str, Any],
    prob_default: float,
    risk_tier: str,
    shap_factors: Dict[str, Any],
    fraud_report: Any,
    rule_decision: Any,
) -> UnderwriterReport:
    """Module-level shortcut for LLMReportGenerator().generate(...)."""
    return LLMReportGenerator().generate(
        fields=fields,
        prob_default=prob_default,
        risk_tier=risk_tier,
        shap_factors=shap_factors,
        fraud_report=fraud_report,
        rule_decision=rule_decision,
    )


# ---------------------------------------------------------------------------
# Smoke test
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    from src.fraud.fraud_engine import FraudReport, FraudFlag
    from src.rules.rule_engine import RuleDecision

    mock_fields = {
        "applicant_name": "Priya Sharma",
        "loan_amount": 25000,
        "annual_income": 72000,
        "dti": 22.5,
        "fico_avg": 695,
        "employment_length": "5 years",
        "home_ownership": "RENT",
        "purpose": "debt_consolidation",
        "revolving_utilization": 61.0,
        "delinquencies_2yrs": 0,
        "public_records": 0,
    }

    mock_shap = {
        "base_value": -1.23,
        "risk_drivers": [
            {"feature": "int_rate",    "value": 14.5,  "shap_contribution": 0.42},
            {"feature": "revol_util",  "value": 61.0,  "shap_contribution": 0.31},
            {"feature": "dti",         "value": 22.5,  "shap_contribution": 0.19},
        ],
        "mitigators": [
            {"feature": "fico_avg",    "value": 695.0, "shap_contribution": -0.38},
            {"feature": "annual_inc",  "value": 72000, "shap_contribution": -0.22},
            {"feature": "open_acc",    "value": 9.0,   "shap_contribution": -0.11},
        ],
    }

    mock_fraud = FraudReport(
        fraud_risk_level="LOW",
        flags=[
            FraudFlag(
                check_name="round_number_loan_amount",
                severity="low",
                description="Loan amount of $25,000 is a round figure.",
                evidence={"loan_amount": 25000},
            )
        ],
        flag_counts={"low": 1, "medium": 0, "high": 0},
    )

    mock_rule = RuleDecision(
        verdict="MANUAL_REVIEW",
        triggered_rules=["model_prob_elevated: P(default)=21.00% >= 20%"],
        rationale=(
            "Application does not meet auto-approve criteria. "
            "Elevated default probability warrants underwriter review."
        ),
        inputs_used={"prob_default": 0.21, "fico_avg": 695, "dti": 22.5},
    )

    print("Generating underwriter report...")
    generator = LLMReportGenerator()
    report = generator.generate(
        fields=mock_fields,
        prob_default=0.21,
        risk_tier="Medium",
        shap_factors=mock_shap,
        fraud_report=mock_fraud,
        rule_decision=mock_rule,
    )

    print(f"\nLLM Provider: {report.llm_provider}")
    print(f"Sections found: {list(report.sections.keys())}")
    print("\n" + report.to_text())
